{
 "title": "kgateway Operations Dashboard",
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "gateway",
    "label": "Gateway",
    "query": {
     "query": "label_values(kgateway_resources_managed,parent)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kgateway_resources_managed,namespace)"
    }
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": {
     "query": "label_values(kgateway_controller_reconciliations_total,controller)"
    }
   },
   {
    "name": "translator",
    "label": "Translator",
    "query": {
     "query": "label_values(kgateway_translator_translations_total,translator)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Translations Running per Translator",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kgateway_translator_translations_running{translator=~\"$translator\"}) by (translator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Reconciliations Running per Controller",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(kgateway_controller_reconciliations_running{controller=~\"$controller\"}) by (controller)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Resources",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kgateway_resources_managed) by (resource)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Translations Rate by Results",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(kgateway_translator_translations_total{translator=~\"$translator\"}[5m])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Reconciliation Rate by Results",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(kgateway_controller_reconciliations_total[5m])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Number of Resources in Collections by Gateways",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kgateway_xds_snapshot_resources) by (gateway, resource)",
     "legendFormat": "Gateway: {{gateway}} - {{resource}}"
    }
   ]
  },
  {
   "title": "Number of Translations Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(kgateway_translator_translations_total{translator=~\"$translator\"}) by (translator)",
     "legendFormat": "{{translator}}"
    }
   ]
  },
  {
   "title": "Number of Controller Reconciliations Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "sum(kgateway_controller_reconciliations_total{controller=~\"$controller\"}) by (controller)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Routing domains (per gateway:port)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kgateway_routing_domains", "legendFormat": "{{gateway}}:{{port}}" }
   ]
  },
  {
   "title": "Status Syncs Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "sum(kgateway_status_syncer_status_syncs_total) by (syncer)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Failed validations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "count(apiserver_request_total{group=~\"gateway.*|solo.*|gloo.*\" ,code=\"422\"}) by (group, resource, subresource)",
     "legendFormat": "{{group}}, {{resource}}"
    }
   ]
  },
  {
   "title": "Control Plane Operation Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "Translation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kgateway_translator_translation_duration_seconds_bucket[5m])) by (le)) OR histogram_quantile(0.99, sum(rate(kgateway_translator_translation_duration_seconds[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(kgateway_translator_translation_duration_seconds_bucket[5m])) by (le)) OR histogram_quantile(0.90, sum(rate(kgateway_translator_translation_duration_seconds[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(kgateway_translator_translation_duration_seconds_bucket[5m])) by (le)) OR histogram_quantile(0.70, sum(rate(kgateway_translator_translation_duration_seconds[5m])))",
     "legendFormat": "p70"
    }
   ]
  },
  {
   "title": "Reconciliation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kgateway_controller_reconcile_duration_seconds_bucket[5m])) by (le)) OR histogram_quantile(0.99, sum(rate(kgateway_controller_reconcile_duration_seconds[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(kgateway_controller_reconcile_duration_seconds_bucket[$__rate_interval])) by (le)) OR histogram_quantile(0.90, sum(rate(kgateway_controller_reconcile_duration_seconds[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(kgateway_controller_reconcile_duration_seconds_bucket[$__rate_interval])) by (le)) OR histogram_quantile(0.70, sum(rate(kgateway_controller_reconcile_duration_seconds[5m])))",
     "legendFormat": "p70"
    }
   ]
  },
  {
   "title": "Status Syncer Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kgateway_status_syncer_status_sync_duration_seconds[5m])) by (le)) OR histogram_quantile(0.99, sum(rate(kgateway_status_syncer_status_sync_duration_seconds[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(kgateway_status_syncer_status_sync_duration_seconds[5m])) by (le)) OR histogram_quantile(0.90, sum(rate(kgateway_status_syncer_status_sync_duration_seconds[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(kgateway_status_syncer_status_sync_duration_seconds[5m])) by (le)) OR histogram_quantile(0.70, sum(rate(kgateway_status_syncer_status_sync_duration_seconds[5m])))",
     "legendFormat": "p70"
    }
   ]
  },
  {
   "title": "p99 XDS Snapshot Sync Latencies by Resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kgateway_resources_xds_snapshot_sync_duration_seconds[5m])) by (le, resource)) OR histogram_quantile(0.99, sum by (le, resource) (rate(kgateway_resources_xds_snapshot_sync_duration_seconds[5m])))",
     "legendFormat": "p99 - {{resource}}"
    }
   ]
  },
  {
   "title": "p99 Reconciliation Latency per Controllers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kgateway_controller_reconcile_duration_seconds{controller=~\"$controller\"}[5m])) by (le, controller)) OR histogram_quantile(0.99, sum by (le, controller) (rate(kgateway_controller_reconcile_duration_seconds{controller=~\"$controller\"}[5m])))",
     "legendFormat": "p99 - {{controller}}"
    }
   ]
  },
  {
   "title": "Resource Status Sync Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kgateway_resources_status_sync_duration_seconds[5m])) by (le)) OR histogram_quantile(0.99, sum(rate(kgateway_resources_status_sync_duration_seconds[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(kgateway_resources_status_sync_duration_seconds[5m])) by (le)) OR histogram_quantile(0.90, sum(rate(kgateway_resources_status_sync_duration_seconds[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(kgateway_resources_status_sync_duration_seconds[5m])) by (le)) OR histogram_quantile(0.70, sum(rate(kgateway_resources_status_sync_duration_seconds[5m])))",
     "legendFormat": "p70"
    }
   ]
  },
  {
   "title": "XDS Snapshot Syncs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "histogram_avg(kgateway_resources_xds_snapshot_sync_duration_seconds)",
     "legendFormat": "{{gateway}}-{{resource}}"
    }
   ]
  },
  {
   "title": "Resource XDS Snapshot Sync Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kgateway_resources_xds_snapshot_sync_duration_seconds[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(kgateway_resources_xds_snapshot_sync_duration_seconds[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(kgateway_resources_xds_snapshot_sync_duration_seconds[5m])))",
     "legendFormat": "p70"
    }
   ]
  }
 ]
}